---
apiVersion: v1
kind: Pod
metadata: 
  name: ocr-api
  labels: 
    app: ocr-api
spec:
  containers:
  - name: ocr-api-container
    image: snowcollege/parakeet:ocr-api-v1.0
    ports:
    - containerPort: 80 
---
apiVersion: v1
kind: Pod
metadata: 
  name: ocr-web
  labels: 
    app: ocr-web
spec:
  containers:
  - name: ocr-web-container
    image: snowcollege/parakeet:sentence-generator
    ports:
    - containerPort: 80 