---
apiVersion: v1
kind: Pod
metadata: 
  name: trigram-api
  labels: 
    app: trigram-api
spec:
  containers:
  - name: trigram-api-container
    image: snowcollege/parakeet:trigram-parcer-v1.0
    ports:
    - containerPort: 80 
    env:
    - name: DB_CONNECTION
      value: "Server=postgres; Port=5432; Database=parakeet; User ID=parakeet; Password=parakeet;"
---
apiVersion: v1
kind: Pod
metadata: 
  name: trigram-web
  labels: 
    app: trigram-web
spec:
  containers:
  - name: trigram-web-container
    image: snowcollege/parakeet:sentence-generator
    ports:
    - containerPort: 80 
    env:
    - name: DB_CONNECTION
      value: "Server=postgres; Port=5432; Database=parakeet; User ID=parakeet; Password=parakeet;"
---
apiVersion: v1
kind: Service
metadata:
  name: trigram-web-service
  labels:
    app: trigram-web-service
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30080
  selector:
    app: trigram-web
---