// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.Data;

namespace TrygramParserAPI.Migrations
{
    [DbContext(typeof(TrygramContext))]
    partial class TrygramContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("TrygramParserAPI.Models.Trygram", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Trygrams");
                });

            modelBuilder.Entity("TrygramParserAPI.Models.TrygramValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrygramKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrygramKey");

                    b.ToTable("TrygramValues");
                });

            modelBuilder.Entity("TrygramParserAPI.Models.TrygramValues", b =>
                {
                    b.HasOne("TrygramParserAPI.Models.Trygram", "Trygram")
                        .WithMany("Values")
                        .HasForeignKey("TrygramKey");
                });
#pragma warning restore 612, 618
        }
    }
}
